### ISSUE TITLE
[BUG] Mismatch with official Prettier plugin `prettier-plugin-tailwindcss`

### ISSUE THREAD

**Issue by lensbart** [francoismassart/eslint-plugin-tailwindcss#171] opened 2022-10-05 21:34 UTC
* eslint-plugin-tailwindcss v3.6.2:
  `absolute left-0 -right-px top-full m-0 block border-l border-b border-neutral-250 bg-neutral-70/97 py-2 shadow backdrop-blur backdrop:bg-neutral-70/80 hires:right-[-0.5px] hires:border-0.5`
* prettier-plugin-tailwindcss v0.1.13
  `backdrop:bg-neutral-70/80 absolute left-0 -right-px top-full m-0 block border-l border-b border-neutral-250 bg-neutral-70/97 py-2 shadow backdrop-blur hires:right-[-0.5px] hires:border-0.5`

with `officialSorting: true`

**Comment by francoismassart** [comment] 2022-10-06 05:06
Hi, I believe this is a duplicate of the following issue https://github.com/francoismassart/eslint-plugin-tailwindcss/issues/155

**Closed by francoismassart** 2022-10-06 05:06 UTC
Labels: bug
