### ISSUE TITLE
[BUG] 'tailwindcss/no-custom-classname' rule breaks ESLint

### ISSUE THREAD

**Issue by KornelijusGlinskas** [francoismassart/eslint-plugin-tailwindcss#46] opened 2021-08-04 14:19 UTC
**Describe the bug**
I've followed the instructions for installation and configuration. Configured with the default preset and it broke ESLint. So instead I've tried to configure rules under the rules section and got the same result. After further investigation, seems that the issue was with  `'tailwindcss/no-custom-classname'` rule, so I removed it and everything started to work just fine.

**Expected behavior**
`'tailwindcss/no-custom-classname'` rule should work and do not break the ESLint.

**Screenshots**
![CleanShot 2021-08-04 at 17 10 08](https://user-images.githubusercontent.com/36265050/128196069-5723129e-a1cb-4290-9711-59dcc883b6a1.png)

**Environment (please complete the following information):**
 - ESLint: 7.32.0
 - OS: macOS
 - Softwares + version used:
     -  VSCode : 1.58.2
     - npm: v7.18.1
     - node: v16.4.0

ESlint config: https://gist.github.com/KornelijusGlinskas/310fd8aed8ba3ca6168615d61b00eda3

**Comment by francoismassart** [comment] 2021-08-05 20:25
Hi there @KornelijusGlinskas,
I'm currently on holiday but I will try to reproduce the issue as soon as I'm back.

It could be even easier for me to do so if you create a complete dummy project that I could just clone and play with.

Cheers

**Comment by thebuilder** [comment] 2021-08-08 15:10
@KornelijusGlinskas could you validate your CSS files contain valid CSS markup? The error seems to indicate it failed to parse a css file because of an extra `}`. Would of course be a nice feature if it actually told you the name of the file it failed to parse.
Does it break if you only run it on a single file?

**Comment by KornelijusGlinskas** [comment] 2021-08-09 20:09
@thebuilder unfortunately, I've only tailwind directives inside my one and only CSS file. 
<img width="625" alt="CleanShot 2021-08-09 at 23 08 30@2x" src="https://user-images.githubusercontent.com/36265050/128767807-95e5d7f8-3544-475f-9760-68b58112cb3b.png">

**Comment by francoismassart** [comment] 2021-09-20 13:33
Hi @KornelijusGlinskas, maybe you could simply omit this file by the [cssFile](https://github.com/francoismassart/eslint-plugin-tailwindcss/blob/master/docs/rules/no-custom-classname.md#cssfiles-default-css-node_modules) option...

You could set it to: `["**/*.css", "!**/node_modules", "resources/assets/spa/styles/app.css"]`

**Comment by francoismassart** [comment] 2021-09-29 10:06
@KornelijusGlinskas, let me know if omitting that css file help or not, closing it for now.

**Closed by francoismassart** 2021-09-29 10:06 UTC
Labels: bug
