### ISSUE TITLE
[Feature request] Support for clsx

### ISSUE THREAD

**Issue by jrozbicki** [francoismassart/eslint-plugin-tailwindcss#13] opened 2021-05-14 09:27 UTC
**Is your feature request related to a problem? Please describe.**
Cannot sort class names when using [clsx](https://www.npmjs.com/package/clsx)

**Describe the solution you'd like**
I would like to have classes sorted when using clsx module `<div className={clsx('absolute bottom-0 w-full h-[270px] flex flex-col)}>`

**Describe alternatives you've considered**
https://github.com/Acidic9/prettier-plugin-tailwind - has that feature, as well as tx.macro support, but doesn't work with eslint

**Additional context**
Works with plain string
![image](https://user-images.githubusercontent.com/35103924/118250759-146a9700-b4a7-11eb-9b54-8fafa574c60d.png)

Doesn't when using clsx
![image](https://user-images.githubusercontent.com/35103924/118250832-277d6700-b4a7-11eb-8334-4c51ca2aa506.png)

Also doesn't work with template literals:
![image](https://user-images.githubusercontent.com/35103924/118251023-5dbae680-b4a7-11eb-8cfb-827cad16d0a4.png)

**Comment by francoismassart** [comment] 2021-05-14 20:43
Hi @jrozbicki ,
I added more tests using `clsx` and I noticed an issue with `clsx` or similar calls when using single line `TemplateLiteral`.
I just published a patch version: `v1.5.4` on npm...

Here is what you should do:

1.  Update the plugin: `npm i eslint-plugin-tailwindcss@1.5.4`
2. Make sure you use add `clsx` to the list of whitelisted `callees` in your [rules options](https://github.com/francoismassart/eslint-plugin-tailwindcss/blob/master/docs/rules/classnames-order.md#options)
3. Update your calls to `clsx` in your codebase... Please use backticks instead of quotes for the classnames list inside the function call.

I am still working on the issue about the `TemplateLiteral` defined directly inside the `className` attribute...

Please let me know if this fix works for you.

**Comment by jrozbicki** [comment] 2021-05-17 10:57
package.json:

`"eslint-plugin-tailwindcss": "1.5.4",`

eslintrc.json:

```
module.exports = {
  root: true,
  env: {
    node: true,
    es6: true,
  },
  parserOptions: { ecmaVersion: 8 },
  ignorePatterns: ['node_modules/*', '.next/*', '.out/*', '!.prettierrc.js'],
  extends: ['eslint:recommended'],
  plugins: ['tailwindcss'],
  overrides: [
    {
      files: ['**/*.jsx', '**/*.js', '**/*.ts', '**/*.tsx'],
      parser: '@typescript-eslint/parser',
      settings: { react: { version: 'detect' } },
      env: {
        browser: true,
        node: true,
        es6: true,
      },
      extends: [
        'eslint:recommended',
        'plugin:@typescript-eslint/recommended',
        'plugin:react/recommended',
        'plugin:react-hooks/recommended',
        'plugin:jsx-a11y/recommended',
        'plugin:prettier/recommended',
      ],
      rules: {
        'react/prop-types': 'off',
        'react/react-in-jsx-scope': 'off',
        'jsx-a11y/anchor-is-valid': 'off',
        '@typescript-eslint/no-unused-vars': ['warn'],
        '@typescript-eslint/explicit-module-boundary-types': 'off',
        'prettier/prettier': ['error', {}, { usePrettierrc: true }],
        'tailwindcss/classnames-order': [
          2,
          {
            callees: ['ctl', 'clsx'],
            prependCustom: true,
          },
        ],
      },
    },
  ],
}
```

Unfortunately I don't see improvement:

![image](https://user-images.githubusercontent.com/35103924/118477769-58f86b80-b70f-11eb-8113-06c27f879a88.png)

With regular quotes it works
![image](https://user-images.githubusercontent.com/35103924/118477713-45e59b80-b70f-11eb-9577-4dbe19af35b8.png)

**Comment by francoismassart** [comment] 2021-05-18 14:59
@jrozbicki this is normal... Right now, the callees are only parsed when they have a single TemplateLiteral argument.
Supporting multiple and/or nested and/or conditional classnames can get very tricky so the plugin only offer limited support for parsing inside the callees.

I'll try to improve this soon but this one is not simple to perform due to the many possibilities it opens.

This feature is a duplicate of https://github.com/francoismassart/eslint-plugin-tailwindcss/issues/15 so I'm closing this one.
I'll @ you when there is something new to test out.

Cheers

**Closed by francoismassart** 2021-05-18 14:59 UTC
Labels: enhancement, work in progress

**Comment by francoismassart** [comment] 2021-05-18 15:01
FYI A working example (with only a single argument) is in the [tests of the `classnames-order` rule](https://github.com/francoismassart/eslint-plugin-tailwindcss/blob/master/tests/lib/rules/classnames-order.js#L286)

**Comment by aguirrealvaro** [comment] 2024-01-19 03:43
Here is the answer https://github.com/francoismassart/eslint-plugin-tailwindcss/issues/252#issuecomment-1580600654
Add this rule to eslint:
```
"tailwindcss/no-custom-classname": [
      "warn",
      {
        callees: ["clsx", "cn],
      },
    ],
```
