### ISSUE TITLE
[Feature request] Migrate to `size` rule

### ISSUE THREAD

**Issue by its-monotype** [francoismassart/eslint-plugin-tailwindcss#299] opened 2023-12-24 14:07 UTC
In TailwindCSS v3.4 [New size-* utilities:](https://tailwindcss.com/blog/tailwindcss-v3-4#new-size-utilities) was added which can replace the same width and height. It would be nice to have a migration rule for that.

**Comment by kachkaev** [comment] 2023-12-24 14:15
Subset / duplicate of https://github.com/francoismassart/eslint-plugin-tailwindcss/issues/297

**Comment by francoismassart** [comment] 2023-12-29 09:48
👋  @its-monotype, I just finished this step on the #297 
You can test it out in the beta channel: `npm i eslint-plugin-tailwindcss@3.14.0-beta.0` and already provide feedback ❤️ in the #297 as well...

Closing as duplicate, be sure to watch the related issue for updates.

**Closed by francoismassart** 2023-12-29 09:48 UTC
Labels: enhancement
